import Navigation from '@/components/nav';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/footer';
import {
  Button,
  Accordion,
  ThemeProvider,
} from '@/utils/material-tailwind-wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-slate-200 min-h-screen'>
        <ThemeProvider>
          <Navigation />
          <div className='my-8'>{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
