export const CATEGORIES = [
  {
    id: 179,
    name: '1) Mecánicos',
    slug: '1-mecanicos',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/1-mecanicos/',
  },
  {
    id: 180,
    name: '2) Autoeléctricos',
    slug: '2-autoelectricos',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/2-autoelectricos/',
  },
  {
    id: 181,
    name: '3) Refaccionarias',
    slug: '3-refaccionarias',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/3-refaccionarias/',
  },
  {
    id: 183,
    name: '4) Vulcanizadoras',
    slug: '4-vulcanizadoras',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/4-vulcanizadoras/',
  },
  {
    id: 184,
    name: '5) Motos',
    slug: '5-motos',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/5-motos/',
  },
  {
    id: 186,
    name: '6) Hojalatería y Pintura',
    slug: '6-hojalateria-y-pintura',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/6-hojalateria-y-pintura/',
  },
  {
    id: 194,
    name: 'Alineación y balanceo',
    slug: 'alineacion-y-balanceo',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/alineacion-y-balanceo/',
  },
  {
    id: 189,
    name: 'Autoboutique',
    slug: 'autoboutique',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/autoboutique/',
  },
  {
    id: 191,
    name: 'Autocristales',
    slug: 'autocristales',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/autocristales/',
  },
  {
    id: 188,
    name: 'Autolavados',
    slug: 'autolavados',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/autolavados/',
  },
  {
    id: 187,
    name: 'Autopartes',
    slug: 'autopartes',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/autopartes/',
  },
  {
    id: 222,
    name: 'Cerrajería Automotriz',
    slug: 'cerrajeria-automotriz',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/cerrajeria-automotriz/',
  },
  {
    id: 182,
    name: 'Detallado Automotriz',
    slug: 'detallado-automotriz',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/detallado-automotriz/',
  },
  {
    id: 193,
    name: 'Escuela de manejo',
    slug: 'escuela-de-manejo',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/escuela-de-manejo/',
  },
  {
    id: 192,
    name: 'Escuela de mecánica',
    slug: 'escuela-de-mecanica',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/escuela-de-mecanica/',
  },
  {
    id: 185,
    name: 'Grúas',
    slug: 'gruas',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/gruas/',
  },
  {
    id: 195,
    name: 'Maquinaria pesada',
    slug: 'maquinaria-pesada',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/maquinaria-pesada/',
  },
  {
    id: 190,
    name: 'Wraps',
    slug: 'wraps',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-categoria/wraps/',
  },
];

export const LOCATIONS = [
  {
    id: 199,
    name: 'Cdmx',
    slug: 'cdmx',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-locacion/cdmx/',
    sub: [
      {
        id: 200,
        name: 'Álvaro Obregón',
        slug: 'alvaro-obregon',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/alvaro-obregon/',
      },
      {
        id: 201,
        name: 'Azcapotzalco',
        slug: 'azcapotzalco',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/azcapotzalco/',
      },
      {
        id: 202,
        name: 'Benito Juárez',
        slug: 'benito-juarez',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/benito-juarez/',
      },
      {
        id: 203,
        name: 'Coyoacán',
        slug: 'coyoacan',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/coyoacan/',
      },
      {
        id: 204,
        name: 'Cuajimalpa',
        slug: 'cuajimalpa',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/cuajimalpa/',
      },
      {
        id: 205,
        name: 'Cuauhtemoc',
        slug: 'cuauhtemoc',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/cuauhtemoc/',
      },
      {
        id: 206,
        name: 'Gustavo A. Madero',
        slug: 'gustavo-a-madero',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/gustavo-a-madero/',
      },
      {
        id: 207,
        name: 'Iztacalco',
        slug: 'iztacalco',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/iztacalco/',
      },
      {
        id: 208,
        name: 'Iztapalapa',
        slug: 'iztapalapa',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/iztapalapa/',
      },
      {
        id: 209,
        name: 'Magdalena Contreras',
        slug: 'magdalena-contreras',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/magdalena-contreras/',
      },
      {
        id: 210,
        name: 'Miguel Hidalgo',
        slug: 'miguel-hidalgo',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/miguel-hidalgo/',
      },
      {
        id: 211,
        name: 'Milpa Alta',
        slug: 'milpa-alta',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/milpa-alta/',
      },
      {
        id: 212,
        name: 'Tláhuac',
        slug: 'tlahuac',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/tlahuac/',
      },
      {
        id: 213,
        name: 'Tlalpan',
        slug: 'tlalpan',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/tlalpan/',
      },
      {
        id: 214,
        name: 'Venustiano Carranza',
        slug: 'venustiano-carranza',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/venustiano-carranza/',
      },
      {
        id: 215,
        name: 'Xochimilco',
        slug: 'xochimilco',
        parent: 199,
        link: 'https://talleresmecanicos.com/listado-locacion/cdmx/xochimilco/',
      },
    ],
  },
  {
    id: 216,
    name: 'Edomex',
    slug: 'edomex',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-locacion/edomex/',
    sub: [
      {
        id: 219,
        name: 'Ecatepec',
        slug: 'ecatepec',
        parent: 216,
        link: 'https://talleresmecanicos.com/listado-locacion/edomex/ecatepec/',
      },
      {
        id: 218,
        name: 'Naucalpan',
        slug: 'naucalpan',
        parent: 216,
        link: 'https://talleresmecanicos.com/listado-locacion/edomex/naucalpan/',
      },
      {
        id: 217,
        name: 'Tlalnepantla',
        slug: 'tlalnepantla',
        parent: 216,
        link: 'https://talleresmecanicos.com/listado-locacion/edomex/tlalnepantla/',
      },
    ],
  },
  {
    id: 44,
    name: 'Jalisco',
    slug: 'jalisco',
    parent: 0,
    link: 'https://talleresmecanicos.com/listado-locacion/jalisco/',
    sub: [
      {
        id: 57,
        name: 'Guadalajara',
        slug: 'guadalajara',
        parent: 44,
        link: 'https://talleresmecanicos.com/listado-locacion/jalisco/guadalajara/',
      },
      {
        id: 197,
        name: 'Tlajomulco',
        slug: 'tlajomulco',
        parent: 44,
        link: 'https://talleresmecanicos.com/listado-locacion/jalisco/tlajomulco/',
      },
      {
        id: 50,
        name: 'Tlaquepaque',
        slug: 'tlaquepaque',
        parent: 44,
        link: 'https://talleresmecanicos.com/listado-locacion/jalisco/tlaquepaque/',
      },
      {
        id: 198,
        name: 'Tonalá',
        slug: 'tonala',
        parent: 44,
        link: 'https://talleresmecanicos.com/listado-locacion/jalisco/tonala/',
      },
      {
        id: 196,
        name: 'Zapopan',
        slug: 'zapopan',
        parent: 44,
        link: 'https://talleresmecanicos.com/listado-locacion/jalisco/zapopan/',
      },
    ],
  },
];
